// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTarget(arg1) {
  return window['go']['main']['App']['AddTarget'](arg1);
}

export function ClearSearchHistory() {
  return window['go']['main']['App']['ClearSearchHistory']();
}

export function DeleteSavedBook(arg1) {
  return window['go']['main']['App']['DeleteSavedBook'](arg1);
}

export function DeleteILLRequest(arg1) {
  return window['go']['main']['App']['DeleteILLRequest'](arg1);
}

export function DeleteTarget(arg1) {
  return window['go']['main']['App']['DeleteTarget'](arg1);
}

export function ExportBookshelf() {
  return window['go']['main']['App']['ExportBookshelf']();
}

export function GetBookDetails(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetBookDetails'](arg1, arg2, arg3);
}

export function ListILLRequests() {
  return window['go']['main']['App']['ListILLRequests']();
}

export function ListSavedBooks() {
  return window['go']['main']['App']['ListSavedBooks']();
}

export function ListSearchHistory() {
  return window['go']['main']['App']['ListSearchHistory']();
}

export function ListTargets() {
  return window['go']['main']['App']['ListTargets']();
}

export function RequestILL(arg1) {
  return window['go']['main']['App']['RequestILL'](arg1);
}

export function SaveBook(arg1) {
  return window['go']['main']['App']['SaveBook'](arg1);
}

export function Search(arg1) {
  return window['go']['main']['App']['Search'](arg1);
}

export function TestTarget(arg1, arg2) {
  return window['go']['main']['App']['TestTarget'](arg1, arg2);
}
