// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddTarget(arg1:main.Target):Promise<void>;

export function ClearSearchHistory():Promise<void>;

export function DeleteSavedBook(arg1:number):Promise<void>;

export function DeleteILLRequest(arg1:number):Promise<void>;

export function DeleteTarget(arg1:string):Promise<void>;

export function ExportBookshelf():Promise<void>;

export function GetBookDetails(arg1:string,arg2:string,arg3:string):Promise<main.BookDetail>;

export function ListILLRequests():Promise<Array<main.ILLRequest>>;

export function ListSavedBooks():Promise<Array<main.SavedBook>>;

export function ListSearchHistory():Promise<Array<string>>;

export function ListTargets():Promise<Array<main.Target>>;

export function RequestILL(arg1:main.ILLRequest):Promise<void>;

export function SaveBook(arg1:main.SearchResult):Promise<void>;

export function Search(arg1:main.SearchParams):Promise<Array<main.SearchResult>>;

export function TestTarget(arg1:string,arg2:number):Promise<main.TestResult>;
